#!/bin/sh
echo "Running cargo fmt --all..."
cargo +nightly fmt --all || exit 1

echo "Running cargo clippy --all..."
cargo clippy --all || exit 1

echo "Running cargo sort workspace..."
cargo sort --workspace || exit 1
