[package]
name = "eth"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
alloy = { version = "0.6.4", features = ["sol-types", "transports", "json", "contract", "pubsub",
"provider-ws", "rpc-types"] }
tokio = { workspace = true }
futures = { workspace = true }



