[package]
name = "keygen"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
types = { workspace = true }
openssl = { workspace = true }
scrypt = "0.11.0"
sha2 = { workspace = true }
aes = "0.8.4"
ctr = "0.9.2"
hex = { workspace = true }
eth-keystore = "0.5.0"
bls_lagrange = { workspace = true }
rand = { workspace = true }
ssv_types = { workspace = true }
base64 = { workspace = true }
alloy = { workspace = true }
