[package]
name = "keygen"
version = "1.2.4"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
clap = { workspace = true }
global_config = { workspace = true }
openssl = { workspace = true }
operator_key = { workspace = true }
rpassword = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }
