use std::{
    collections::{HashMap, HashSet},
    fs::File,
    path::Path,
    time::Duration,
};

use multi_index_map::MultiIndexMap;
use once_cell::sync::OnceCell;
use openssl::{pkey::Public, rsa::Rsa};
use r2d2_sqlite::SqliteConnectionManager;
use rusqlite::{Transaction, params};
use ssv_types::{Cluster, ClusterId, CommitteeId, Operator, OperatorId, Share, ValidatorMetadata};
use tokio::sync::{
    watch,
    watch::{Receiver, Ref},
};
use types::{Address, PublicKeyBytes};

pub use crate::{error::DatabaseError, state::NetworkState};

/// All the shares that belong to the current operator.
/// IMPORTANT: There are parts of the code that assume this only contains shares that belong to the
/// current operator. If this ever changes, make sure to update the code accordingly.
#[derive(Debug, Clone, MultiIndexMap)]
pub struct ShareIndexed {
    #[multi_index(hashed_unique)]
    pub validator_pubkey: PublicKeyBytes,

    #[multi_index(hashed_non_unique)]
    pub cluster_id: ClusterId,

    #[multi_index(hashed_non_unique)]
    pub owner: Address,

    #[multi_index(hashed_non_unique)]
    pub committee_id: CommitteeId,

    pub share: Share,
}

/// Metadata for all validators in the network
#[derive(Debug, Clone, MultiIndexMap)]
pub struct MetadataIndexed {
    #[multi_index(hashed_unique)]
    pub validator_pubkey: PublicKeyBytes,

    #[multi_index(hashed_non_unique)]
    pub cluster_id: ClusterId,

    #[multi_index(hashed_non_unique)]
    pub owner: Address,

    #[multi_index(hashed_non_unique)]
    pub committee_id: CommitteeId,

    pub metadata: ValidatorMetadata,
}

/// All the clusters in the network
#[derive(Debug, Clone, MultiIndexMap)]
pub struct ClusterIndexed {
    #[multi_index(hashed_unique)]
    pub cluster_id: ClusterId,

    #[multi_index(hashed_non_unique)]
    pub owner: Address,

    #[multi_index(hashed_non_unique)]
    pub committee_id: CommitteeId,

    pub cluster: Cluster,
}

mod cluster_operations;
mod error;
mod keysplit_operations;
mod operator_operations;
mod share_operations;
mod sql_operations;
mod state;
mod validator_operations;

#[cfg(test)]
mod tests;

const POOL_SIZE: u32 = 1;
const CONNECTION_TIMEOUT: Duration = Duration::from_secs(5);

type Pool = r2d2::Pool<SqliteConnectionManager>;
type PoolConn = r2d2::PooledConnection<SqliteConnectionManager>;

// The actual map types are generated by the macro and are named:
// - MultiIndexShareIndexedMap
// - MultiIndexMetadataIndexedMap
// - MultiIndexClusterIndexedMap
//
// Information that needs to be accessed via multiple different indices
struct MultiState {
    shares: MultiIndexShareIndexedMap,
    validator_metadata: MultiIndexMetadataIndexedMap,
    clusters: MultiIndexClusterIndexedMap,
    // Be careful when adding new maps here. If you really must to, it must be updated in the
    // operations files
}

// General information that can be single index access
#[derive(Debug, Default)]
struct SingleState {
    /// The ID of our own operator. This is determined via events when the operator is
    /// registered with the network. Therefore, this may not be available right away if the
    /// operator is running but has not been registered with the network contract yet.
    id: Option<OperatorId>,
    /// The last block that was processed
    last_processed_block: u64,
    /// All of the operators in the network
    operators: HashMap<OperatorId, Operator>,
    /// All of the Clusters that we are a memeber of
    clusters: HashSet<ClusterId>,
    /// Nonce of the owner account
    nonces: HashMap<Address, u16>,
}

#[derive(Debug)]
enum PubkeyOrId {
    Pubkey(Rsa<Public>),
    Id(OperatorId),
}

/// Top level NetworkDatabase that contains in memory storage for quick access
/// to relevant information and a connection to the database
pub struct NetworkDatabase {
    /// The public key or ID of our operator
    operator: PubkeyOrId,
    /// Custom state stores for easy data access
    state: watch::Sender<NetworkState>,
    /// Connection to the database
    conn_pool: Pool,
}

impl NetworkDatabase {
    /// Construct a new NetworkDatabase at the given path and the Public Key of the current operator
    pub fn new(path: &Path, pubkey: &Rsa<Public>) -> Result<Self, DatabaseError> {
        let conn_pool = Self::open_or_create(path)?;
        let operator = PubkeyOrId::Pubkey(pubkey.clone());
        let state = watch::Sender::new(NetworkState::new_with_state(&conn_pool, &operator)?);
        Ok(Self {
            operator,
            state,
            conn_pool,
        })
    }

    /// Act as if we had the pubkey of a certain operator
    pub fn new_as_impostor(path: &Path, operator: &OperatorId) -> Result<Self, DatabaseError> {
        let conn_pool = Self::open_or_create(path)?;
        let operator = PubkeyOrId::Id(*operator);
        let state = watch::Sender::new(NetworkState::new_with_state(&conn_pool, &operator)?);
        Ok(Self {
            operator,
            state,
            conn_pool,
        })
    }

    pub fn state(&self) -> Ref<'_, NetworkState> {
        self.state.borrow()
    }

    pub fn watch(&self) -> Receiver<NetworkState> {
        self.state.subscribe()
    }

    /// Update the last processed block number in the database
    /// Also, trigger a notification for other code to act on the new state
    pub fn processed_block(
        &self,
        block_number: u64,
        tx: &Transaction<'_>,
    ) -> Result<(), DatabaseError> {
        tx.prepare_cached(sql_operations::UPDATE_BLOCK_NUMBER)?
            .execute(params![block_number])?;
        self.state
            .send_modify(|state| state.single_state.last_processed_block = block_number);
        Ok(())
    }

    // Open an existing database at the given `path`, or create one if none exists.
    fn open_or_create(path: &Path) -> Result<Pool, DatabaseError> {
        if path.exists() {
            Self::open_conn_pool(path)
        } else {
            Self::create(path)
        }
    }

    // Build a new connection pool
    fn open_conn_pool(path: &Path) -> Result<Pool, DatabaseError> {
        let manager = SqliteConnectionManager::file(path);
        // some other args here
        let conn_pool = Pool::builder()
            .max_size(POOL_SIZE)
            .connection_timeout(CONNECTION_TIMEOUT)
            .build(manager)?;
        Ok(conn_pool)
    }

    // Create a database at the given path.
    fn create(path: &Path) -> Result<Pool, DatabaseError> {
        let _file = File::options()
            .write(true)
            .read(true)
            .create_new(true)
            .open(path)?;

        // restrict file permissions
        let conn_pool = Self::open_conn_pool(path)?;
        let conn = conn_pool.get()?;

        // create all of the tables
        conn.execute_batch(include_str!("table_schema.sql"))?;
        Ok(conn_pool)
    }

    // Open a new connection
    pub fn connection(&self) -> Result<PoolConn, DatabaseError> {
        Ok(self.conn_pool.get()?)
    }

    /// for convenience: Apply a modification to the state without triggering a notification
    /// This will be done at the end of a block via `processed_block` to avoid spamming
    fn modify_state(&self, f: impl FnOnce(&mut NetworkState)) {
        self.state.send_if_modified(|state| {
            f(state);
            false
        });
    }
}

/// A helper to get the operator ID of the current operator. Caches the ID after successfully
/// retrieving it to avoid locking the state further.
#[derive(Clone)]
pub enum OwnOperatorId {
    /// The operator ID was known when the `OwnOperatorId` was created.
    Known(OperatorId),
    /// The operator ID was not known when the `OwnOperatorId` was created. It will be retrieved
    /// from the `receiver` and cached in the `id` on first success.
    FromState {
        receiver: Receiver<NetworkState>,
        /// We use a `OnceLock` so that `get` can be called without a mutable reference.
        id: OnceCell<OperatorId>,
    },
}

impl OwnOperatorId {
    /// Creates the `OwnOperatorId` to either immediately store the operator ID or to recheck it on
    /// later `get` calls.
    pub fn new(receiver: Receiver<NetworkState>) -> Self {
        if let Some(operator_id) = receiver.borrow().get_own_id() {
            Self::Known(operator_id)
        } else {
            Self::FromState {
                receiver,
                id: OnceCell::new(),
            }
        }
    }

    /// Get the operator ID if it is available. Caches the ID internally after the first successful
    /// call to avoid locking the state in the future. This is possible because the own Operator ID
    /// never changes.
    pub fn get(&self) -> Option<OperatorId> {
        match self {
            Self::Known(id) => Some(*id),
            Self::FromState { receiver, id } => {
                // Switch to `std`'s OnceLock as soon as `get_or_try_init` is stable
                id.get_or_try_init(|| receiver.borrow().get_own_id().ok_or(()))
                    .ok()
                    .copied()
            }
        }
    }
}

impl From<OperatorId> for OwnOperatorId {
    fn from(operator_id: OperatorId) -> Self {
        Self::Known(operator_id)
    }
}
