use std::{fs::File, io::BufReader};

use serde::{Deserialize, Serialize};

use crate::{error::KeysplitError, util::hex_to_buffer};

// Representation of a keystore file generated by the deposit cli
// https://github.com/ssvlabs/ssv-keys/blob/df1f0a5edd7ce95ad5ab0298c58e83908216557b/src/lib/EthereumKeyStore/EthereumKeyStore.ts#L7
#[derive(Serialize, Deserialize, Debug)]
pub struct Keystore {
    pub crypto: Crypto,
    pub description: String,
    pub pubkey: String,
    pub path: String,
    pub uuid: String,
    pub version: u8,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Crypto {
    pub kdf: Kdf,
    pub checksum: Checksum,
    pub cipher: Cipher,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Kdf {
    pub function: KdfType,
    pub params: KdfparamsType,
    #[serde(deserialize_with = "hex_to_buffer")]
    pub message: Vec<u8>,
}

#[derive(Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum KdfType {
    Pbkdf2,
    Scrypt,
}

#[derive(Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(untagged)]
pub enum KdfparamsType {
    Pbkdf2 {
        c: u32,
        dklen: u8,
        prf: String,
        #[serde(deserialize_with = "hex_to_buffer")]
        salt: Vec<u8>,
    },
    Scrypt {
        dklen: u8,
        n: u32,
        p: u32,
        r: u32,
        #[serde(deserialize_with = "hex_to_buffer")]
        salt: Vec<u8>,
    },
}

#[derive(Serialize, Deserialize, Debug)]
pub struct KdfParams {
    pub dklen: u32,
    pub n: u32,
    pub r: u32,
    pub p: u32,
    pub salt: String,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Checksum {
    pub function: String,
    pub params: ChecksumParams,
    #[serde(deserialize_with = "hex_to_buffer")]
    pub message: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct ChecksumParams {}

#[derive(Serialize, Deserialize, Debug)]
pub struct Cipher {
    pub function: String,
    pub params: CipherParams,
    #[serde(deserialize_with = "hex_to_buffer")]
    pub message: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct CipherParams {
    #[serde(deserialize_with = "hex_to_buffer")]
    pub iv: Vec<u8>,
}

// Parse the keystore file into a usable format
pub fn parse_keystore(keystore: File) -> Result<Keystore, KeysplitError> {
    let reader = BufReader::new(keystore);
    let keystore: Keystore = serde_json::from_reader(reader)
        .map_err(|e| KeysplitError::Keystore(format!("Invalid keystore: {e}")))?;
    Ok(keystore)
}
