[package]
name = "bls_lagrange"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[features]
default = ["blst_single_thread"]
blst_single_thread = []

[dependencies]
bls = { workspace = true }
blst = { workspace = true }
rand = { workspace = true }
zeroize = { workspace = true }
