[package]
name = "client"
version = "1.2.0"
authors = ["Sigma Prime <contact@sigmaprime.io"]
edition = { workspace = true }

[lib]
name = "client"
path = "src/lib.rs"

[dependencies]
anchor_validator_store = { workspace = true }
axum = { workspace = true }
beacon_node_fallback = { workspace = true }
clap = { workspace = true }
database = { workspace = true }
duties_tracker = { workspace = true }
eth = { workspace = true }
eth2 = { workspace = true }
fdlimit = "0.3"
fork = { workspace = true }
global_config = { workspace = true }
http_api = { workspace = true }
http_metrics = { workspace = true }
hyper = { workspace = true }
logging = { workspace = true }
message_receiver = { workspace = true }
message_sender = { workspace = true }
message_validator = { workspace = true }
metrics = { workspace = true }
multiaddr = { workspace = true }
network = { workspace = true }
network_utils = { workspace = true }
openssl = { workspace = true }
operator_doppelganger = { workspace = true }
operator_key = { workspace = true }
parking_lot = { workspace = true }
processor = { workspace = true }
qbft_manager = { workspace = true }
sensitive_url = { workspace = true }
signature_collector = { workspace = true }
slashing_protection = { workspace = true }
slot_clock = { workspace = true }
ssv_types = { workspace = true }
subnet_service = { workspace = true }
task_executor = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }
validator_metrics = { workspace = true }
validator_services = { workspace = true }
version = { workspace = true }
zeroize = { workspace = true }
