pub use sync::{Config, SsvEventSyncer};
mod error;
mod event_parser;
mod event_processor;
mod generated;
pub mod index_sync;
mod metrics;
mod network_actions;
mod sync;
mod util;
pub mod voluntary_exit_processor;
pub use metrics::EXECUTION_EVENTS_PROCESSED;
