pub use sync::{Config, SsvEventSyncer};
mod error;
mod event_parser;
pub mod event_processor;
pub mod generated;
pub mod index_sync;
mod metrics;
mod sync;
pub mod util;
pub mod voluntary_exit_processor;
pub use database::SlashingProtection;
pub use metrics::EXECUTION_EVENTS_PROCESSED;
