use std::{hash::Hasher, time::Duration};

use gossipsub::{ConfigBuilderError, MessageAuthenticity, ValidationMode};
use libp2p::{identify, ping, swarm::NetworkBehaviour};
use prometheus_client::registry::Registry;
use thiserror::Error;
use twox_hash::XxHash64;
use types::{ChainSpec, EthSpec};
use version::version_with_platform;

use crate::{
    Config,
    behaviour::BehaviourError::Gossipsub,
    discovery::{Discovery, FIND_NODE_QUERY_CLOSEST_PEERS},
    handshake,
    peer_manager::PeerManager,
    scoring::peer_score_config::{peer_score_params, peer_score_thresholds},
};

const MAX_TRANSMIT_SIZE_BYTES: usize = 5_000_000;

/// Custom message ID function matching Go-SSV implementation.
/// Uses xxhash64 of the full message to ensure uniqueness across operators.
///
/// Algorithm:
/// 1. Return empty MessageId for empty messages
/// 2. Compute xxhash64 of the message data
/// 3. Convert hash to little-endian bytes in a 12-byte buffer: the first 8 bytes contain the
///    little-endian hash, and the last 4 bytes are zero-padded to match the Go implementation
///    format.
/// 4. Return MessageId from the buffer
fn ssv_message_id(message: &gossipsub::Message) -> gossipsub::MessageId {
    if message.data.is_empty() {
        return gossipsub::MessageId::from("");
    }

    let mut hasher = XxHash64::with_seed(0);
    hasher.write(&message.data);
    let hash = hasher.finish();

    let mut buf = [0u8; 12];
    buf[0..8].copy_from_slice(&hash.to_le_bytes());

    gossipsub::MessageId::from(buf.as_slice())
}

#[derive(Debug, Error)]
pub enum BehaviourError {
    #[error("Gossipsub config error: {0}")]
    Gossipsub(String),

    #[error("Gossipsub config builder error: {0}")]
    GossipsubConfigBuilderError(#[from] ConfigBuilderError),

    #[error("Discovery error: {0}")]
    Discovery(#[from] crate::discovery::DiscoveryError),
}

#[derive(NetworkBehaviour)]
pub struct AnchorBehaviour {
    /// Provides IP addresses and peer information.
    pub identify: identify::Behaviour,
    /// Used for connection health checks.
    pub ping: ping::Behaviour,
    /// The routing pub-sub mechanism for Anchor.
    pub gossipsub: gossipsub::Behaviour,
    /// Discv5 Discovery protocol.
    pub discovery: Discovery,
    /// Anchor peer manager, wrapping libp2p behaviours with minimal added logic for peer
    /// selection.
    pub peer_manager: PeerManager,

    pub handshake: handshake::Behaviour,
}

impl AnchorBehaviour {
    pub async fn new<E: EthSpec>(
        local_keypair: libp2p::identity::Keypair,
        network_config: &Config,
        metrics_registry: &mut Registry,
        spec: &ChainSpec,
    ) -> Result<Self, BehaviourError> {
        let identify = {
            let local_public_key = local_keypair.public();
            let identify_config = identify::Config::new("anchor".into(), local_public_key)
                .with_agent_version(version_with_platform())
                .with_cache_size(0);
            identify::Behaviour::new(identify_config)
        };

        let slots_per_epoch = E::slots_per_epoch();
        let seconds_per_slot = spec.seconds_per_slot;
        let duplicate_cache_time = Duration::from_secs(slots_per_epoch * seconds_per_slot); // 6.4 min TODO make this configurable

        let gossipsub_config = gossipsub::ConfigBuilder::default()
            .duplicate_cache_time(duplicate_cache_time) // This is equivalent to seen_msg_ttl used in PeerScoreParams in go ssv
            .message_id_fn(ssv_message_id)
            .flood_publish(false)
            .validation_mode(ValidationMode::Permissive)
            // Do not punish identical messages generated by us and other nodes. This can happen for
            // `Decided` messages.
            .allow_self_origin(true)
            .mesh_n(8) // D
            .mesh_n_low(6) // Dlo
            .mesh_n_high(12) // Dhi
            .mesh_outbound_min(4) // Dout
            .heartbeat_interval(Duration::from_millis(700))
            .history_length(6)
            .history_gossip(4)
            .max_ihave_length(1500)
            .max_ihave_messages(32)
            // `SignedSSVMessage` has a full data field with max 4,194,532 bytes, so 5M bytes seems
            // like a reasonable upper bound for that and the rest of the message.
            .max_transmit_size(MAX_TRANSMIT_SIZE_BYTES)
            .validate_messages()
            .build()?;

        let mut gossipsub =
            gossipsub::Behaviour::new(MessageAuthenticity::RandomAuthor, gossipsub_config)
                .map_err(|e| Gossipsub(e.to_string()))?;
        gossipsub = gossipsub.with_metrics(
            metrics_registry.sub_registry_with_prefix("gossipsub"),
            gossipsub::MetricsConfig::default(),
        );

        // Add peer scoring if not disabled
        if !network_config.disable_gossipsub_peer_scoring {
            let slots_per_epoch = E::slots_per_epoch();
            let slot_duration = Duration::from_secs(spec.seconds_per_slot);
            let one_epoch_duration = slot_duration * slots_per_epoch as u32;
            let score_params = peer_score_params(one_epoch_duration);
            let score_thresholds = peer_score_thresholds();

            gossipsub
                .with_peer_score(score_params, score_thresholds)
                .map_err(|e| {
                    Gossipsub(format!(
                        "Failed to activate the peer scoring system with the given parameters: {e}"
                    ))
                })?;
        }

        let discovery = {
            // Build and start the discovery sub-behaviour
            let mut discovery = Discovery::new(local_keypair.clone(), network_config).await?;
            // start searching for peers
            discovery.discover_peers(FIND_NODE_QUERY_CLOSEST_PEERS);
            discovery
        };

        let peer_manager = {
            let slots_per_epoch = E::slots_per_epoch();
            let slot_duration = Duration::from_secs(spec.seconds_per_slot);
            let one_epoch_duration = slot_duration * slots_per_epoch as u32;
            PeerManager::new(network_config, one_epoch_duration)
        };

        let handshake = {
            let domain_type: String = network_config.domain_type.into();
            let node_info = handshake::node_info::NodeInfo::new(
                domain_type,
                Some(handshake::node_info::NodeMetadata {
                    node_version: version_with_platform(),
                    execution_node: "geth/v1.10.8".to_string(),
                    consensus_node: "lighthouse/v1.5.0".to_string(),
                    subnets: "00000000000000000000000000000000".to_string(),
                }),
            );
            handshake::Behaviour::new(local_keypair, node_info)
        };

        Ok(AnchorBehaviour {
            identify,
            ping: ping::Behaviour::default(),
            gossipsub,
            discovery,
            peer_manager,
            handshake,
        })
    }
}

#[cfg(test)]
mod tests {
    use gossipsub::Message;
    use libp2p::PeerId;

    use super::*;

    #[test]
    fn test_message_id_empty_message() {
        let message = Message {
            source: None,
            data: vec![],
            sequence_number: None,
            topic: gossipsub::IdentTopic::new("test").hash(),
        };

        let msg_id = ssv_message_id(&message);
        assert_eq!(msg_id, gossipsub::MessageId::from(""));
    }

    #[test]
    fn test_message_id_consistency() {
        let data = b"test message data";
        let message = Message {
            source: Some(PeerId::random()),
            data: data.to_vec(),
            sequence_number: Some(1),
            topic: gossipsub::IdentTopic::new("test").hash(),
        };

        let msg_id_1 = ssv_message_id(&message);
        let msg_id_2 = ssv_message_id(&message);

        // Same message should produce same ID
        assert_eq!(msg_id_1, msg_id_2);
    }

    #[test]
    fn test_message_id_different_messages() {
        let message1 = Message {
            source: Some(PeerId::random()),
            data: b"message 1".to_vec(),
            sequence_number: Some(1),
            topic: gossipsub::IdentTopic::new("test").hash(),
        };

        let message2 = Message {
            source: Some(PeerId::random()),
            data: b"message 2".to_vec(),
            sequence_number: Some(2),
            topic: gossipsub::IdentTopic::new("test").hash(),
        };

        let msg_id_1 = ssv_message_id(&message1);
        let msg_id_2 = ssv_message_id(&message2);

        // Different messages should produce different IDs
        assert_ne!(msg_id_1, msg_id_2);
    }

    #[test]
    fn test_message_id_format() {
        let data = b"test data";
        let message = Message {
            source: Some(PeerId::random()),
            data: data.to_vec(),
            sequence_number: Some(1),
            topic: gossipsub::IdentTopic::new("test").hash(),
        };

        let msg_id = ssv_message_id(&message);

        // Verify the message ID is created from a 12-byte buffer
        let msg_id_bytes = msg_id.0;
        assert_eq!(msg_id_bytes.len(), 12);

        // Verify last 4 bytes are zeros (as per Go implementation)
        assert_eq!(&msg_id_bytes[8..12], &[0u8, 0u8, 0u8, 0u8]);
    }

    #[test]
    fn test_message_id_xxhash_computation() {
        let data = b"test message";

        // Manually compute expected hash
        let mut hasher = XxHash64::with_seed(0);
        hasher.write(data);
        let expected_hash = hasher.finish();
        let mut expected_buf = [0u8; 12];
        expected_buf[0..8].copy_from_slice(&expected_hash.to_le_bytes());

        let message = Message {
            source: Some(PeerId::random()),
            data: data.to_vec(),
            sequence_number: Some(1),
            topic: gossipsub::IdentTopic::new("test").hash(),
        };

        let msg_id = ssv_message_id(&message);
        assert_eq!(msg_id.0, expected_buf);
    }

    #[test]
    fn test_message_id_uniqueness_across_operators() {
        // This test verifies that identical message bodies from different operators
        // produce the same message ID (since we hash the full message data)
        let same_data = b"identical message body";

        let message1 = Message {
            source: Some(PeerId::random()),
            data: same_data.to_vec(),
            sequence_number: Some(1),
            topic: gossipsub::IdentTopic::new("test").hash(),
        };

        let message2 = Message {
            source: Some(PeerId::random()),
            data: same_data.to_vec(),
            sequence_number: Some(2),
            topic: gossipsub::IdentTopic::new("test").hash(),
        };

        let msg_id_1 = ssv_message_id(&message1);
        let msg_id_2 = ssv_message_id(&message2);

        // Same data should produce same message ID
        assert_eq!(msg_id_1, msg_id_2);
    }
}
