[package]
name = "integration"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.3", features = ["ws"] }
clap = { workspace = true }
client = { workspace = true }
discv5 = { workspace = true }
environment = { workspace = true }
ethereum_serde_utils = { workspace = true }
execution_layer = { workspace = true }
futures = { workspace = true }
futures-util = "0.3.31"
kzg = { workspace = true }
lighthouse_network = { workspace = true }
logging = { workspace = true }
network = { workspace = true }
node_test_rig = { workspace = true }
parking_lot = { workspace = true }
sensitive_url = { workspace = true }
serde_json = { workspace = true }
ssv_network_config = { workspace = true }
task_executor = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = "0.26.2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
types = { workspace = true }
