[package]
name = "integration"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { workspace = true }
serde_json = { workspace = true }
node_test_rig = { git = "https://github.com/ThreeHrSleep/lighthouse", rev = "6b54fe0" }
logging = { git = "https://github.com/ThreeHrSleep/lighthouse", rev = "6b54fe0"}
environment = { git = "https://github.com/ThreeHrSleep/lighthouse",  rev = "6b54fe0"}
kzg = { git = "https://github.com/ThreeHrSleep/lighthouse", rev ="6b54fe0" }
execution_layer = { git = "https://github.com/ThreeHrSleep/lighthouse", rev = "6b54fe0" }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
env_logger = "0.11.6"
rayon = "1.10.0"
tokio = { workspace = true }
client = { workspace = true }


