[package]
name = "cli"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
axum = { workspace = true }
beacon_node_fallback = { workspace = true }
clap = { workspace = true }
ethereum_hashing = { workspace = true }
global_config = { workspace = true }
keygen = { workspace = true }
keysplit = { workspace = true }
logging = { workspace = true }
version = { workspace = true }
