[package]
name = "operator_doppelganger"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
database = { workspace = true }
parking_lot = { workspace = true }
slot_clock = { workspace = true }
ssv_types = { workspace = true }
task_executor = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }
