[package]
name = "anchor-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[features]
arbitrary-fuzz = ["ssv_types/arbitrary-fuzz"]

[dependencies]
database = { workspace = true }
ethereum_ssz = { workspace = true }
libfuzzer-sys = "0.4"
message_validator = { workspace = true }
openssl = { workspace = true }
slot_clock = { workspace = true }
ssv_types = { workspace = true, features = ["arbitrary-fuzz"] }
tokio = { workspace = true }
types = { workspace = true }

[[bin]]
name = "validate_target"
path = "fuzz_targets/validate_target.rs"
test = false
doc = false
bench = false
