[package]
name = "subnet_service"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
alloy = { workspace = true }
database = { workspace = true }
ethereum_serde_utils = "0.7.0"
fork = { workspace = true }
gossipsub = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
slot_clock = { workspace = true }
ssv_network_config = { workspace = true }
ssv_types = { workspace = true }
task_executor = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
typenum = { workspace = true }
types = { workspace = true }
