#MD013 line length: https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
# Set to false as this will also interfere with help_x.md files, and it is not necessary to comply with the line length of 80
MD013: false

# MD024: set siblings_only to true so that same headings with different parent headings are allowed
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md024.md
MD024:
  siblings_only: true

# MD033 in-line html: https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
# In-line html is fine in the markdown files, so this is set to false
MD033: false

# MD036 set to false to preserve the emphasis on deprecation notice on key-management.md (a heading is not necessary)
MD036: false
