[book]
language = "en"
multilingual = false
src = "src"
title = "Anchor Book"
author = "Sigma Prime"

[output.html]
additional-css =["src/css/custom.css"]
default-theme = "coal"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

